default_stages: ['pre-commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: local-golangci-lint-fmt
        name: golangci-lint fmt
        entry: golangci-lint fmt
        language: system
        pass_filenames: false
        types: [go]

      - id: local-go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]

      - id: local-golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        pass_filenames: false
        require_serial: true
        types: [go]

      - id: local-go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
        require_serial: true
        types: [go]
        stages: [pre-push]

      - id: local-justfile
        name: justfile check
        entry: just --check --fmt
        language: system
        files: ^justfile$
        pass_filenames: false
        require_serial: true

      - id: local-zizmor
        name: zizmor
        entry: zizmor
        language: system
        files: ^\.github\/workflows\/.*\.(yml|yaml)$
        require_serial: true
        types: [yaml]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 953e1ba4599cc3143122ed5c3e8de3d6dfd5524d  # v4.16.2
    hooks:
      - id: commitizen
